version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    tty: true
    working_dir: /workspace/nextjs_and_nestjs/nextjs
    volumes:
      - ../../.:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - 127.0.0.1:80:80
volumes:
  node_modules:
