version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    tty: true
    working_dir: /workspace/nestjs/backend
    volumes:
      - ../../.:/workspace
      - backend_node_modules:/workspace/nestjs/backend/node_modules
    ports:
      - 127.0.0.1:80:80
volumes:
  backend_node_modules:
